version: '2'

services:
   mysql:
     image: mysql:5.7
     volumes:
       - "/data/docker/mysql/gvv:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: toto

   myadmin:
     depends_on:
       - mysql
     image: phpmyadmin/phpmyadmin
     links:
       - "mysql:db"
     ports:
       - "9000:80"
     restart: always

#  php-dev is build from the Dockerfile in the current directory
#      image: php:7.0-apache     
   php-dev:
      build:
       .
      links:
       - "mysql:db"
      volumes:
       - "/home/frederic/git/citemplate:/var/www/html"
      ports:
       - "9001:80"


